services:
  mariadb:
    image: mariadb:11.8
    environment:
      # En temps normal, il faudrait mettre ces informations sensibles dans un fichier caché .env qui ne serait pas versionné sur Git
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: doliuser
      MYSQL_PASSWORD: dolipassword
    volumes:
      - db_data:/var/lib/mysql

  dolibarr:
    image: dolibarr/dolibarr:24.0.0
    ports:
      - "8080:80"
    environment:
      # En temps normal, il faudrait mettre ces informations sensibles dans un fichier caché .env qui ne serait pas versionné sur Git
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: doliuser
      DOLI_DB_PASSWORD: dolipassword
      DOLI_DB_NAME: dolibarr
    depends_on:
      # Force Docker à préparer le conteneur mariadb avant de lancer celui-ci
      - mariadb
    volumes:
      # Persistance des fichiers du site et des documents générés par l'ERP (factures, devis)
      - dolibarr_html:/var/www/html
      - dolibarr_docs:/var/www/documents

# Déclaration obligatoire des disques virtuels utilisés par les conteneurs ci-dessus
volumes:
  db_data:
  dolibarr_html:
  dolibarr_docs: